services:
  e2e:
    build: .
    image: bootcamp2-chrome-extension:latest
    environment:
      - CI=true
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app
    command: npm test
    shm_size: '2gb'